version: "3.8"
services:
  app:
    image: ghcr.io/jappyjan/fablab-slicer:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./slicer-configs:/app/slicer-configs:ro
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
