version: "3.8"

services:
  fablab-slicer:
    # runs on port 8080 - needs to be exposed to the outside world
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
    #ports:
    #  - "8080:8080"
    volumes:
      - slicer-configs:/app/slicer-configs

volumes:
  slicer-configs:
    external: true
    name: slicer-configs
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./slicer-configs
